// ignore_for_file: constant_identifier_names

import 'package:travel_app/models/category.dart';
import 'package:travel_app/models/trip.dart';

const Categories_data = [
  Category(id: 'c1', title: 'cities', imgsrc: 'images/Ancient.png'),
  Category(id: 'c2', title: 'desert', imgsrc: 'images/desert.png'),
  Category(id: 'c3', title: 'Forests', imgsrc: 'images/Forests.png'),
  Category(id: 'c4', title: 'mountains', imgsrc: 'images/mountains.png'),
  Category(id: 'c5', title: 'summer', imgsrc: 'images/summer.png'),
  Category(id: 'c6', title: 'winter', imgsrc: 'images/winter.png'),
];
const Trips_data = [
  Trip(
    id: 'm1',
    categories: [
      'c4',
    ],
    title: 'The Alps',
    tripType: TripType.Exploration,
    season: Season.Winter,
    imageUrl: 'images/alp.jpg',
    duration: 20,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: false,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm2',
    categories: [
      'c4',
    ],
    title: 'south mountain',
    tripType: TripType.Exploration,
    season: Season.Winter,
    imageUrl: 'images/southmountain.jpg',
    duration: 10,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: false,
    isForFamilies: false,
    isInWinter: false,
  ),
  Trip(
    id: 'm3',
    categories: [
      'c4',
    ],
    title: 'hieght mountain',
    tripType: TripType.Recovery,
    season: Season.Winter,
    imageUrl: 'images/height.jpg',
    duration: 45,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: false,
    isForFamilies: false,
    isInWinter: true,
  ),
  Trip(
    id: 'm4',
    categories: [
      'c5',
      'c3',
    ],
    title: 'large lake',
    tripType: TripType.Activities,
    season: Season.Spring,
    imageUrl: 'images/large_lake.jpg',
    duration: 60,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: false,
    isForFamilies: false,
    isInWinter: false,
  ),
  Trip(
    id: 'm5',
    categories: [
      'c5',
      'c3',
    ],
    title: 'small lake',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'images/smalllake.jpg',
    duration: 15,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: true,
    isForFamilies: false,
    isInWinter: true,
  ),
  Trip(
    id: 'm6',
    categories: [
      'c3',
    ],
    title: 'special lake',
    tripType: TripType.Exploration,
    season: Season.Summer,
    imageUrl: 'images/speciallake.jpg',
    duration: 240,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: true,
    isForFamilies: false,
    isInWinter: false,
  ),
  Trip(
    id: 'm7',
    categories: [
      'c5',
    ],
    title: 'First Beach',
    tripType: TripType.Exploration,
    season: Season.Winter,
    imageUrl: 'images/beach.jpg',
    duration: 20,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: true,
    isForFamilies: false,
    isInWinter: false,
  ),
  Trip(
    id: 'm8',
    categories: [
      'c5',
    ],
    title: 'large Beach',
    tripType: TripType.Recovery,
    season: Season.Spring,
    imageUrl: 'images/beach1.jpg',
    duration: 35,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: true,
    isForFamilies: false,
    isInWinter: true,
  ),
  Trip(
    id: 'm9',
    categories: [
      'c5',
    ],
    title: 'stone Beach',
    tripType: TripType.Exploration,
    season: Season.Summer,
    imageUrl: 'images/beach2.jpg',
    duration: 45,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: true,
    isForFamilies: false,
    isInWinter: false,
  ),
  Trip(
    id: 'm10',
    categories: [
      'c2',
    ],
    title: 'largest desert',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'images/desert1.jpg',
    duration: 30,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm11',
    categories: [
      'c4',
      'c1',
    ],
    title: 'westen desert',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'images/desert2.jpg',
    duration: 30,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm12',
    categories: [
      'c2',
    ],
    title: 'sand desert',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'images/sanddesert.jpg',
    duration: 30,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm13',
    categories: [
      'c1',
    ],
    title: 'first city',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'images/city1.jpg',
    duration: 30,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm14',
    categories: [
      'c1',
    ],
    title: 'second city',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'images/city2.jpg',
    duration: 30,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm15',
    categories: [
      'c5',
    ],
    title: 'old city',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'images/oldcity.jpg',
    duration: 30,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm16',
    categories: [
      'c6',
    ],
    title: 'ski sport',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'images/ski.jpg',
    duration: 30,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
  Trip(
    id: 'm17',
    categories: [
      'c6',
      'c2',
    ],
    title: 'sky dive',
    tripType: TripType.Activities,
    season: Season.Winter,
    imageUrl: 'images/skydive.jpg',
    duration: 30,
    activities: [
      'Visit archaeological sites',
      'walking tour',
      'Visiting commercial centers for shopping',
      'Eat lunch',
      'Enjoying the beautiful scenery'
    ],
    program: [
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae, corporis.',
    ],
    isInSummer: true,
    isForFamilies: true,
    isInWinter: true,
  ),
];
